In [1]:
import pandas as pd

In [2]:
airbnb = pd.read_csv ('/Users/clarkeashleigh/Downloads/airbnb_test_users.csv')

In [3]:
airbnb.head()

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser
0,5uwns89zht,7/1/2014,2.014070e+13,NaN,FEMALE,35.0,facebook,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari
1,jtl0dijy2j,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari
2,xx0ulgorjt,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome
3,6c6puo6ix0,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,IE
4,czqhjk3yfe,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Safari

In [ ]:
### Average Age

In [4]:
age = airbnb.groupby ('first_browser')['age'].mean()

In [5]:
age.head()

first_browser
-unknown-             41.526894
AOL Explorer          60.000000
Android Browser       42.822148
Apple Mail            26.750000
BlackBerry Browser    34.600000
Name: age, dtype: float64

In [ ]:
## Total signup flow

In [10]:
sign_up = airbnb.groupby ('first_device_type')['signup_flow'].sum()

In [11]:
sign_up.head()

first_device_type
Android Phone      90521
Android Tablet      5969
Desktop (Other)       50
Mac Desktop         5736
Other/Unknown       4826
Name: signup_flow, dtype: int64

In [ ]:
### ADDING ANOTHER DATASET (country)

In [12]:
country = pd.read_csv ('/Users/clarkeashleigh/Downloads/airbnb_sample_submission.csv')

In [13]:
country.head()

           id country
0  5uwns89zht     NDF
1  jtl0dijy2j     NDF
2  xx0ulgorjt     NDF
3  6c6puo6ix0     NDF
4  czqhjk3yfe     NDF

In [19]:
airbnb2 = pd.merge(airbnb, country)

In [20]:
airbnb2.head()

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country
0,5uwns89zht,7/1/2014,2.014070e+13,NaN,FEMALE,35.0,facebook,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF
1,jtl0dijy2j,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF
2,xx0ulgorjt,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome,NDF
3,6c6puo6ix0,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,IE,NDF
4,czqhjk3yfe,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Safari,NDF

In [ ]:
### ADDING ANOTHER DATASET (users)

In [21]:
users = pd.read_csv ('/Users/clarkeashleigh/Downloads/airbnb_users.csv')

In [22]:
users.head()

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country_destination
0,gxn3p5htnn,6/28/2010,2.009030e+13,NaN,-unknown-,NaN,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,NDF
1,820tgsjxq7,5/25/2011,2.009050e+13,NaN,MALE,38.0,facebook,0,en,seo,google,untracked,Web,Mac Desktop,Chrome,NDF
2,4ft3gnwmtx,9/28/2010,2.009060e+13,8/2/2010,FEMALE,56.0,basic,3,en,direct,direct,untracked,Web,Windows Desktop,IE,US
3,bjjt8pjhuk,12/5/2011,2.009100e+13,9/8/2012,FEMALE,42.0,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Firefox,other
4,87mebub9p4,9/14/2010,2.009120e+13,2/18/2010,-unknown-,41.0,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,US

In [24]:
airbnb2.head()

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country
0,5uwns89zht,7/1/2014,2.014070e+13,NaN,FEMALE,35.0,facebook,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF
1,jtl0dijy2j,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF
2,xx0ulgorjt,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome,NDF
3,6c6puo6ix0,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,IE,NDF
4,czqhjk3yfe,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Safari,NDF

In [29]:
airbnb3 = pd.concat ([airbnb2, users])

In [30]:
airbnb3.head()

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country,country_destination
0,5uwns89zht,7/1/2014,2.014070e+13,NaN,FEMALE,35.0,facebook,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF,NaN
1,jtl0dijy2j,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Moweb,iPhone,Mobile Safari,NDF,NaN
2,xx0ulgorjt,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome,NDF,NaN
3,6c6puo6ix0,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,IE,NDF,NaN
4,czqhjk3yfe,7/1/2014,2.014070e+13,NaN,-unknown-,NaN,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Safari,NDF,NaN